### PR TITLE
完善了自述文件，添加了语言切换跳链，新增虚拟环境安装运行脚本

### PR DESCRIPTION
**Pull request by WavesMan**
完善了自述文件的简体中文版本，为双语自述文件添加了语言切换跳链
跳链仅适用于Fork分支 [WavesMan:main](https://github.com/WavesMan/ExVR/tree/main) ，PR需要修改跳链内容
创建了以虚拟环境状态安装所需依赖包 (`0.Install_in_venv.bat`)
创建了以虚拟环境启动 `main.py` (`1.Start_in_venv.bat`)

The Simplified Chinese version of the self-description file has been improved, and a language switch link has been added to the bilingual self-description file.  
The link is only applicable to the Fork branch [WavesMan:main](https://github.com/WavesMan/ExVR/tree/main), and the PR needs to modify the link content.  
Created a batch file to install the required dependencies in a virtual environment (`0.Install_in_venv.bat`).  
Created a batch file to start `main.py` in a virtual environment (`1.Start_in_venv.bat`).

### CODE REVIEW

**Comment by WavesMan** [comment]
冲突问题在 #16  中已解决，可直接套用 [hand.py](https://github.com/xiaofeiyu0723/ExVR/blob/main/tracker/hand/hand.py) 的内容

The conflict issue has been resolved in #16  , and the content from [hand.py](https://github.com/xiaofeiyu0723/ExVR/blob/main/tracker/hand/hand.py) can be directly applied.

**Comment by xiaofeiyu0723** [comment]
For the 0.Install_in_venv.bat and 1.Start_in_venv.bat, developers can directly use the [requirements.txt](https://github.com/xiaofeiyu0723/ExVR/blob/main/requirements.txt) file to install the related packages, so these scripts are unnecessary.

**Comment by WavesMan** [comment]
> 对于0.Install_in_venv.bat和1.Start_in_venv.bat，开发者可以直接使用 [requirements.txt](https://github.com/xiaofeiyu0723/ExVR/blob/main/requirements.txt) 文件来安装相关的包，所以这些脚本就不需要了。

对于两个脚本是为了方便快捷安装虚拟环境，并安装依赖。可以为其他没有python基础的VRChat玩家提供更方便的使用体验。
The two scripts are designed to quickly and easily install the virtual environment and dependencies. They provide a more convenient user experience for VRChat players who have no background in Python.

**Comment by xiaofeiyu0723** [comment]
Users can use the [release version](https://github.com/xiaofeiyu0723/ExVR/releases/tag/0.5.2).

**Comment by WavesMan** [comment]
> Users can use the [release version](https://github.com/xiaofeiyu0723/ExVR/releases/tag/0.5.2).

The deletion has been completed, and a PR can now be made.

**Pull request merged**
